commented x64

diff --git a/.github/workflows/multiarchtesting.yml b/.github/workflows/multiarchtesting.yml
--- a/.github/workflows/multiarchtesting.yml
+++ b/.github/workflows/multiarchtesting.yml
@@ -28,18 +28,18 @@ jobs:
           dotnet --list-sdks
           dotnet --info
 
-      - name: Use x64 .NET SDK explicitly via path
-        run: |
-          echo "x64 SDK location:"
-          DOTNET_ROOT_X64=$(find $RUNNER_TOOL_CACHE/dotnet -type d -name 'x64' | head -n1)
-          # Use .NET x64
-          if [ -d "$DOTNET_ROOT_X64" ]; then
-            "$DOTNET_ROOT_X64/dotnet" --version
-            "$DOTNET_ROOT_X64/dotnet" --info
-          else
-            echo "x64 SDK not found!"
-            exit 1
-          fi
+      # - name: Use x64 .NET SDK explicitly via path
+      #   run: |
+      #     echo "x64 SDK location:"
+      #     DOTNET_ROOT_X64=$(find $RUNNER_TOOL_CACHE/dotnet -type d -name 'x64' | head -n1)
+      #     # Use .NET x64
+      #     if [ -d "$DOTNET_ROOT_X64" ]; then
+      #       "$DOTNET_ROOT_X64/dotnet" --version
+      #       "$DOTNET_ROOT_X64/dotnet" --info
+      #     else
+      #       echo "x64 SDK not found!"
+      #       exit 1
+      #     fi
 
       - name: Use arm64 .NET SDK explicitly via path
         run: |
